mysite/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

# set the application namespace
# https://docs.djangoproject.com/en/2.0/intro/tutorial03/
app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path("profile/", views.ProfileView.as_view(), name="profile"),
    path("profile/edit/", views.ProfileEditView.as_view(), name="prof_edit"),
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
]

mysite/chat/urls.py
from django.urls import path
from . import views

app_name = "chat"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("chat/", views.ChatView.as_view(), name="index"),
    path("chat/<str:room_name>/", views.RoomView.as_view(), name="room"),
    path("groupselect/", views.GroupSelectView.as_view(), name="group_select")
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("chat.urls")),     # トップページの表示
    path("accounts/", include("django.contrib.auth.urls")),   # 認証
    path("accounts/", include("accounts.urls")),    # アカウントに関するページ
    path('admin/', admin.site.urls),    # 管理インターフェース
]


mysite/chat/models.py
from django.db import models
from django.db.models import Manager
from django.utils import timezone
from accounts.models import User


# Create your models here.


# groupテーブルに対応するモデルクラスの作成
class Group(models.Model):
    group_id = models.AutoField(verbose_name="group_id", primary_key=True)
    group_name = models.CharField(verbose_name="group_name", max_length=20)
    objects = models.Manager()

    def __str__(self):
        return self.group_name

    class Meta:
        db_table = "group"


# chat_historyテーブルに対応するモデルクラスの作成
class ChatHistory(models.Model):
    chat_id = models.BigAutoField(verbose_name="chat_id", primary_key=True)
    text = models.TextField(verbose_name="text", max_length=500)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="user_id")
    datetime = models.DateTimeField(default=timezone.now, verbose_name="datetime")
    group_id = models.ForeignKey(Group, on_delete=models.CASCADE, verbose_name="group_id")
    objects = models.Manager()

    def __str__(self):
        return self.text

    class Meta:
        db_table = "chat_history"


# group_memberテーブルに対応するモデルクラスの作成
class GroupMember(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="user_id", primary_key=True)
    group_id = models.ForeignKey(Group, on_delete=models.CASCADE, verbose_name="group_id")
    objects = models.Manager()

    class Meta:
        db_table = "group_member"
        # 疑似的に複合キーのような状態にする
        constraints = [
            models.UniqueConstraint(fields=["user_id", "group_id"], name="belongs")
        ]


mysite/chat/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import GroupMember, Group
from accounts.models import User


# Create your views here.

class HomeView(LoginRequiredMixin, generic.TemplateView):
    template_name = "chat/home.html"

"""
@login_required
def home(request):
    # group_list = Group.objects
    if request.user.is_authenticated:
        return render(request, "chat/home.html")
    else:
        return redirect("login")
"""


class ChatView(LoginRequiredMixin, generic.TemplateView):
    template_name = "chat/index.html"

"""
@login_required
def index(request):
    if request.user.is_authenticated:
        return render(request, "chat/index.html")
    else:
        return redirect("login")
"""


"""　エラーでわかんない　やりたい事：ログインしたユーザーの所属しているグループを中間テーブル経由で取得して、それをcontextとしてテンプレートに投げたい。
class GroupSelectView(LoginRequiredMixin, generic.TemplateView):
    def get(self, request, *args, **kwargs):
        user = User.objects.get(user_id=request.user.user_id)
        belong = GroupMember.objects.filter(user_id=user.user_id)
        group = Group.objects.filter(group_id=belong)

        return render(request, "chat/group_select.html", {"group": group})
"""


class RoomView(LoginRequiredMixin, generic.TemplateView):
    template_name = "chat/chatroom.html"

"""
@login_required
def chatroom(request, room_name):
    if request.user.is_authenticated:
        return render(request, "chat/chatroom.html", {"room_name": room_name})
    else:
        return redirect("login")
"""

mysite/templates/chat/chatroom.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{room_name}}{% endblock  %}

{% block body %}
<section class="chat_wrap">
    <div class="group_select">
        <div class="group_icon">
            <i class="far fa-comment"></i>
            <i class="fas fa-users"></i>
        </div>
    </div>
    <div class="chat">
        <div class="talk_wrap">
            <div class="answer_box">
                <div class="answer_balloon"></div>
            </div>
        </div>
        <div class="comment">
            <input class="message_input" type="text">
            <button class="box" type="submit">送信</button>
            {{ room_name|json_script:"room_name" }}
        </div>
    </div>
</section>
{% endblock %}

{% block extra_js %}
<script src="{% static 'js/chat.js' %}"></script>
{% endblock %}

mysite/templates/chat/group_select.html
{% extends 'base.html' %}

{% block title %}グループ選択{% endblock %}

{% block body %}

{% if group %}
    <ul>
    {% for g in group %}
        {{ f.as_li }}
    {% endfor %}
    </ul>
{% endif %}

{% endblock %}

mysite/templates/chat/home.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
</head>
<body>
<a href="{% url 'chat:index' %}">チャットへ</a>
<a href="#">グループへ</a>
<a href="{% url 'accounts:profile' %}">プロフィールを確認</a>
<a href="{% url 'logout' %}">ログアウト</a>
</body>
</html>

mysite/templates/chat/index.html
<!DOCTYPE html>
{% load static %}
    <html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>chat</title>
</head>
<body>
    <h1>チャット部屋</h1>
    <input id="room-name-input" type="text" size="50">
    <br>
    <input id="room-name-submit" type="submit" value="決定">

    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <script>
        $(function(){
            $("#room-name-input").keypress(function (e) {
                if (e.which == 13) {
                    document.querySelector("#room-name-submit").click();
                }
            });
        });

        document.querySelector("#room-name-submit").onclick = function(e){
            var roomName = document.querySelector("#room-name-input").value;
            window.location.pathname = "/chat/" + roomName + "/";
        }
    </script>
</body>
</html>

mysite/templates/chat/room.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>room</title>
</head>
<body>
    <textarea id="chat-log" cols="100" rows="20"></textarea>
    <br>
    <input id="chat-message-input" type="text" size="100">
    <br>
    <input id="chat-message-submit" type="submit" value="送信">
    {{ room_name|json_script:"room_name" }}

<script>
    const roomName = JSON.parse(document.getElementById("room_name").textContent);
    const chatSocket = new WebSocket(
        "ws://" + window.location.host + "/ws/chat/" + roomName + "/"
    );
    console.log(chatSocket);

    chatSocket.onmessage = function(e){
        const data = JSON.parse(e.data);
        var message = data["message"];
        document.querySelector("#chat-log").value += (message + "\n");
    }

    chatSocket.onclose = function(e){
        console.error("通信に失敗しました。");
    }

    document.querySelector("#chat-message-input").focus();
    document.querySelector("#chat-message-input").onkeyup = function(e){
        if(e.KeyCode === 13){
            document.querySelector("#chat-message-submit").click();
        }
    }

    document.querySelector("#chat-message-submit").onclick = function(e){
        const messageInputDom = document.querySelector("#chat-message-input");
        const message = messageInputDom.value;
        chatSocket.send(JSON.stringify({
            "message": message,
        }));
        messageInputDom.value = "";
    }

</script>
</body>
</html>