mysite/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

# set the application namespace
# https://docs.djangoproject.com/en/2.0/intro/tutorial03/
app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path("profile/", views.ProfileView.as_view(), name="profile"),
    path("profile/edit/", views.ProfileEditView.as_view(), name="prof_edit"),
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
]

mysite/chat/urls.py
from django.urls import path
from . import views

app_name = "chat"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("chat/", views.ChatView.as_view(), name="index"),
    path("chat/<str:room_name>/", views.RoomView.as_view(), name="room"),
    path("groupselect/", views.GroupSelectView.as_view(), name="group_select")
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("chat.urls")),     # トップページの表示
    path("accounts/", include("django.contrib.auth.urls")),   # 認証
    path("accounts/", include("accounts.urls")),    # アカウントに関するページ
    path('admin/', admin.site.urls),    # 管理インターフェース
]


mysite/accounts/models.py
from django.core.mail import send_mail
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.contrib.auth.base_user import BaseUserManager
from django.contrib import auth
from django.utils.translation import gettext as _


# Create your models here.


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, username, email, password, **extra_fields):
        """
        Create and save a user with the given username, email, and password.
        """
        if not username:
            raise ValueError('ユーザーネームを設定してください')
        email = self.normalize_email(email)
        username = self.model.normalize_username(username)
        user = self.model(username=username, email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, username, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(username, email, password, **extra_fields)

    def create_superuser(self, username, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(username, email, password, **extra_fields)

    def with_perm(self, perm, is_active=True, include_superusers=True, backend=None, obj=None):
        if backend is None:
            backends = auth._get_backends(return_tuples=True)
            if len(backends) == 1:
                backend, _ = backends[0]
            else:
                raise ValueError(
                    '複数の認証が構成されているため、'
                    '”backend”引数を指定する必要があります。'
                )
        elif not isinstance(backend, str):
            raise TypeError(
                '引数”backend”はドット付きのインポートパス文字列である必要があります (got %r).'
                % backend
            )
        else:
            backend = auth.load_backend(backend)
        if hasattr(backend, 'with_perm'):
            return backend.with_perm(
                perm,
                is_active=is_active,
                include_superusers=include_superusers,
                obj=obj,
            )
        return self.none()


class User(AbstractBaseUser, PermissionsMixin):
    username_validator = UnicodeUsernameValidator()

    user_id = models.AutoField(verbose_name="user_id", primary_key=True)
    username = models.CharField(_('username'), max_length=20, validators=[username_validator], unique=True)
    email = models.EmailField(_('email'), unique=True)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),

    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')
        db_table = "user"

        # 下記をそのままにしておくと抽象クラスととみなされインスタンスできないのでここだけコメントアウトが必要
        # abstract = True

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

    def __str__(self):
        return self.username

mysite/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import User


class SingUpForm(UserCreationForm):
    username = forms.CharField(max_length=20, required=True, help_text="ユーザーネーム", label="username")
    email = forms.EmailField(max_length=200, help_text="メールアドレス", label="email")
    password1 = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")


class ProfileForm(forms.Form):
    username = forms.CharField(max_length=20, label="ユーザーネーム")
    email = forms.EmailField(max_length=200, label="メールアドレス")

mysite/accounts/views.py
from django.urls import reverse_lazy
from django.views import generic
from django.views import View
from django.shortcuts import render, redirect
from .models import User
from .forms import SingUpForm
from .forms import ProfileForm


class SignUpView(generic.CreateView):
    form_class = SingUpForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'


class ProfileView(View):
    def get(self, request, *args, **kwargs):
        user_data = User.objects.get(user_id=request.user.user_id)

        return render(request, "accounts/profile.html", {"user_data": user_data})


class ProfileEditView(View):
    def get(self, request):
        user_data = User.objects.get(user_id=request.user.user_id)
        form = ProfileForm(
            request.POST or None,
            initial={
                "username": user_data.username,
                "email": user_data.email,
            }
        )

        return render(request, "accounts/prof_edit.html", {"form": form})

    def post(self, request):
        form = ProfileForm(request.POST or None)
        if form.is_valid():
            user_data = User.objects.get(user_id=request.user.user_id)
            user_data.username = form.cleaned_data["username"]
            user_data.email = form.cleaned_data["email"]
            user_data.save()
            return redirect("http://127.0.0.1:8000/accounts/profile")

        return render(request, "accounts/profile.html", {"form": form})

mysite/templates/accounts/prof_edit.html
{% extends 'base.html' %}

{% block title %}プロフィール編集{% endblock %}

{% block body %}


<div class="py-3">
    <div class="container">
        <div style="font-size: 30px;">アカウント情報変更</div><br>
        <!-- フォーム -->
        <form method="post">
        {% csrf_token %}
 
            <!-- ユーザ名 -->
            <div class="form-group row">
                <label for="username" class="col-md-3 col-form-label">
                    ユーザーネーム <span class="badge badge-warning">必須</span>
                </label>
                <div class="col-md-9">
                    {{ form.username }}
                </div>
            </div>
            <!-- /ユーザ名 -->
 
            <!-- メールアドレス -->
            <div class="form-group row">
                <label for="email" class="col-md-3 col-form-label">
                    メールアドレス <span class="badge badge-warning">必須</span>
                </label>
                <div class="col-md-9">
                    {{ form.email }}
                </div>
            </div>
 
            {# エラーメッセージを表示 #}
            {% if form.errors %}
                {% for field in form %}
                    {% for error in field.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                 {% endfor %}
            {% endif %}
 
            <!-- 確認ボタン -->
            <div class="form-group row justify-content-end">
                <div class="col-md-9">
                    <button type="submit" class="btn btn-primary">変更する</button>
                </div>
            </div>
 
        </form>
        <!-- /フォーム -->
    </div>
</div>


{% endblock %}

mysite/templates/accounts/profile.html
{% extends 'base.html' %}

{% block title %}プロフィール{% endblock %}

{% block body %}

<div class="card card-profile my-5 mx-auto">
    <div class="card-body">
        <h5 class="card-title text-center">プロフィール</h5>
        <table class="profile_table mb-4">
            <tbody>
                <tr>
                    <th class="header">ユーザーネーム</th>
                    <td class="data">{{ user_data.username }}</td>
                </tr>
                <tr>
                    <th class="header">メールアドレス</th>
                    <td class="data">{{ user_data.email }}</td>
                </tr>
            </tbody>
        </table>
        <div class="button mx-auto">
            <a href="{% url 'accounts:prof_edit' %}" class="btn btn-lg btn-warning btn-block">プロフィールを編集</a>
        </div>
    </div>
</div>

{% endblock %}

mysite/templates/accounts/signup.html
{% extends 'base.html' %}

{% block title %}新規登録{% endblock %}

{% block body %}
<section class="common-form">
    <div class="py-3">
    <div class="container">
        <div style="font-size: 30px;">新規登録</div><br>
        <!-- フォーム -->
        <form method="post">
        {% csrf_token %}
 
            <!-- ユーザ名 -->
            <div class="form-group row">
                <label for="username" class="col-md-3 col-form-label">
                    ユーザーネーム <span class="badge badge-warning">必須</span>
                </label>
                <div class="col-md-9">
                    {{ form.username }}
                </div>
            </div>
            <!-- /ユーザ名 -->
 
            <!-- メールアドレス -->
            <div class="form-group row">
                <label for="email" class="col-md-3 col-form-label">
                    メールアドレス <span class="badge badge-warning">必須</span>
                </label>
                <div class="col-md-9">
                    {{ form.email }}
                </div>
            </div>

            <!-- メールアドレス -->
            <div class="form-group row">
                <label for="email" class="col-md-3 col-form-label">
                    パスワード <span class="badge badge-warning">必須</span>
                </label>
                <div class="col-md-9">
                    {{ form.password1 }}
                </div>
            </div>

            <!-- メールアドレス -->
            <div class="form-group row">
                <label for="email" class="col-md-3 col-form-label">
                    パスワード（確認用） <span class="badge badge-warning">必須</span>
                </label>
                <div class="col-md-9">
                    {{ form.password2 }}
                </div>
            </div>
 
            {# エラーメッセージを表示 #}
            {% if form.errors %}
                {% for field in form %}
                    {% for error in field.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                 {% endfor %}
            {% endif %}
 
            <!-- 確認ボタン -->
            <div class="form-group row justify-content-end">
                <div class="col-md-9">
                    <button type="submit" class="btn btn-primary btn-lg">登録</button>
                </div>
            </div>
 
        </form>
</section>
{% endblock %}
</body>
</html>